name: Bug report
about: Create a report to help us improve
labels: 'Requires Testing'
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report for FastAsyncWorldEdit! Fill out the following form to your best ability to help us fix the problem.
        Only use this if you're absolutely sure that you found a bug and can reproduce it. For anything else, use: [our Discord server](https://discord.gg/intellectualsites) or [the wiki](https://wiki.intellectualsites.com/FastAsyncWorldEdit).
  - type: dropdown
    attributes:
      label: Server Implementation
      description: Which server Implementation are you using? If your server implementation is not listed, it is not supported. Switch to a supported version first.
      multiple: false
      options:
        - Paper
        - Spigot
        - Tuinity
        - Purpur
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Server Version
      description: Which server version version you using? If your server version is not listed, it is not supported. Update to a supported version first.
      multiple: false
      options:
        - '1.16.5'
        - '1.15.2'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      description: Steps to reproduce this behaviour
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behaviour
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots / Videos
      description: If applicable, add screenshots to help explain your problem.
  - type: input
    attributes:
      label: Error log (if applicable)
      description: If you are reporting a console error, upload any relevant log excerpts to either https://haste.athion.net/ or https://gist.github.com, save and the paste the link in this box.
  - type: input
    attributes:
      label: Fawe Debugpaste
      description: Run `/fawe debugpaste` in your console or ingame and provide the output link here.
    validations:
      required: true
  - type: input
    attributes:
      label: Fawe Version
      description: What version of Fawe are you running? (`/version FastAsyncWorldEdit`)
      placeholder: "For example: FastAsyncWorldEdit version 1.16-606;4a6af71"
    validations:
      required: true