name: Feature request
description: Suggest an idea for this project
labels: 'Enhancement'

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request for FastAsyncWorldEdit! Fill out the following form to your best ability to help us understand your feature request and greately improve the change of it getting added.
        For anything else than a feature request, use: [our Discord server](https://discord.gg/intellectualsites) or [the wiki](https://github.com/IntellectualSites/FastAsyncWorldEdit/wiki).

  - type: textarea
    attributes:
      label: What feature do you want to see added?
      description: A clear and concise description of your feature request.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Are there any alternatives?
      description: List any alternatives you might have tried
    validations:
      required: true

  - type: textarea
    attributes:
      label: Anything else?
      description: You can provide additional context below.
