name: Announce release on discord
on:
  release:
    types: [published]

jobs:
  send_announcement:
    runs-on: ubuntu-latest
    steps:
      - name: send custom message with args
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: FastAsyncWorldEdit Release
          DISCORD_AVATAR: https://raw.githubusercontent.com/IntellectualSites/Assets/main/plugins/FastAsyncWorldEdit/FastAsyncWorldEdit.png
        uses: Ilshidur/action-discord@0.3.2
        with:
          args: |
            "<@&525015715300900875> <@&706463154804097105> <@&671372968462516240>"
            ""
            "<:fawe:730750370984493106> **FastAsyncWorldEdit ${{ github.event.release.tag_name }} has been released!**"
            ""
            "Click here to view changelog: https://github.com/IntellectualSites/FastAsyncWorldEdit/releases/tag/${{ github.event.release.tag_name }}"
            ""
            "The download is available at:"
            "- Spigot: <https://www.spigotmc.org/resources/13932/>"
            "- Modrinth: <https://modrinth.com/plugin/fastasyncworldedit/version/${{ github.event.release.tag_name }}>"
            "- CurseForge: <https://www.curseforge.com/minecraft/bukkit-plugins/fawe>"
