name: Build Branch
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to build'
        required: true
        default: 'feat/caption-minimessage-support'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          cache: gradle
          java-version: 25

      - name: Build
        run: ./gradlew build -s

      - name: Archive Bukkit Plugin
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-Bukkit
          path: worldedit-bukkit/build/libs/FastAsyncWorldEdit-*.jar

      - name: Archive Core Library
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-Core
          path: worldedit-core/build/libs/FastAsyncWorldEdit-*.jar

      - name: Archive CLI
        uses: actions/upload-artifact@v7
        with:
          name: FastAsyncWorldEdit-CLI
          path: worldedit-cli/build/libs/*.jar
