name: draft release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      contents: write # to create a GitHub release (release-drafter/release-drafter)

    if: ${{ github.repository_owner == 'IntellectualSites' }}
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Release Draft
        id: release-drafter
        uses: release-drafter/release-drafter@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
